---

- name: Download Node Exporter
  get_url:
    url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: "/tmp/node_exporter.tar.gz"

- name: Extract Node Exporter tarball
  unarchive:
    src: "/tmp/node_exporter.tar.gz"
    dest: "/usr/local/bin"
    remote_src: yes
    extra_opts: [--strip-components=1]
    creates: "/usr/local/bin/node_exporter"

- name: Copy Node Exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: '0644'

- name: Reload systemd to pick up node_exporter service
  systemd:
    daemon_reload: yes

- name: Ensure Node Exporter service is running and enabled
  systemd:
    name: node_exporter
    state: started
    enabled: yes
